### ISSUE TITLE
CSS in Stylesheet Datei auslagern

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/fau-cris#180]
Bei verschiedenen Websites mit dem CRIS-Plugin wird dieses Inline-Stylesheet erzeugt:

```html
<style type="text/css">
#nav .level2 li.cris-last {
border-bottom: 1px solid #aaa;
padding-bottom: 10px;
margin-bottom: 10px;
}
#nav .level2 li.cris-first {
border-top: 1px solid #aaa;
padding-top: 10px;
}
#nav .level2 li.cris-first:before {
content: 'Research Areas';
display:block;
color: #fff;
font-weight: bold;
margin-bottom: 5px;
}
#nav .level2 li.cris-last a {
border-bottom-color: transparent;
}
</style>
```

Bitte das in eine Stylesheet-Datei auslagern und grundsätzlich keine Inline-Styles machen.
Ggf. sind Body-Classes zu verwenden um die Ausgabe zu steuern.

Falls die Sprache der Grund für das Setzen des content ist - auch diese kann man in der CSS-Datei festlegen und zwar z.B. so:

```css
#nav .level2 li.cris-first:before {
    content: 'Forschungsgebiete';
}
:lang(en) #nav .level2 li.cris-first:before {
    content: 'Research Areas';
}

```
